<?php if(!empty($errors) && is_array($errors) && count($errors) > 0) : ?>
    <?php foreach ($errors as $error) : ?>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <?=$error?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<div class="panel panel-primary panel-border">

    <div class="panel-heading">
        <h3 class="panel-title"><?= $locale->_('Buy for btc') ?></h3>
    </div>

    <div class="panel-body">
        <?php if(!empty($qrcode) && !empty($address)) : ?>
            <div class="row">
                <div class="col-lg-12">
                    <div class="col-lg-6">
                        <div class="portlet text-center">
                            <div class="portlet-heading bg-primary">
                                <h3 class="portlet-title">
                                    <?= $locale->_('Bitcoin data') ?>
                                </h3>
                                <div class="portlet-widgets">
                                    <a href="javascript:;" data-toggle="reload"><i class="ion-refresh"></i></a>
                                    <span class="divider"></span>
                                    <a data-toggle="collapse" data-parent="#accordion1" href="#bg-primary"><i class="ion-minus-round"></i></a>
                                    <span class="divider"></span>
                                    <a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div id="bg-primary" class="panel-collapse collapse in">
                                <div class="portlet-body">
                                    <span class="label label-info"><?= $locale->_('BTC address send to') ?>: <?=$address?></span>
                                    <span class="label label-info"><?= $locale->_('BTC amount send to') ?>: <?=$amount_in_btc?></span>
                                    <p></p>
                                    <hr>
                                    <span class="label label-info"><?= $locale->_('Your qrcode link') ?></span>
                                    <p></p>
                                    <img src="data:image/png;base64,<?=$qrcode?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <div class="col-lg-6">
                <form class="form-horizontal" role="form" method="post">
                    <div class="form-group">
                        <label for="account" class="col-sm-3 control-label"><?= $locale->_('Account') ?></label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="account" name="account" required="" value="<?=$account?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="amount" class="col-sm-3 control-label"><?= $locale->_('Amount') ?></label>
                        <div class="col-sm-9">
                            <input type="number" class="form-control" id="amount" name="amount" required="" min="0.01" step="0.01" placeholder="0.00">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="amount" class="col-sm-3 control-label"><?= $locale->_('Asset') ?></label>
                        <div class="col-sm-9">
                            <select name="asset" id="asset" class="form-control">
                                <?php foreach ($assets as $asset) : ?>
                                    <option value="<?=$asset?>"><?=$asset?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-b-0">
                        <div class="col-sm-offset-3 col-sm-9">
                            <button type="submit" class="btn btn-primary btn-custom waves-effect w-md waves-light m-b-5"><?= $locale->_('Submit') ?></button>
                        </div>
                    </div>
                </form>
            </div>
        <?php endif; ?>
    </div>
</div>