version: '2'
services:
  npm:
    container_name: smartmoney-abs-npm
    image: smartmoney/abs/npm
    build: docker/nodejs
    volumes:
      - ./app:/app

  postgres:
    restart: always
    container_name: smartmoney-abs-postgre
    image: smartmoney/abs/postgre
    build: docker/postgres
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root

  php-fpm:
    restart: always
    container_name: smartmoney-abs-fpm
    image: smartmoney/abs/fpm
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./logs/php-fpm/:/logs
    links:
      - postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    depends_on:
      - npm
      - postgres
    env_file:
      - .env

  nginx:
    restart: always
    container_name: smartmoney-abs-nginx
    image: smartmoney/abs/nginx
    build: docker/nginx
    ports:
      - "8092:80"
    volumes:
      - ./app:/app
      - ./logs/nginx/:/logs
    links:
      - php-fpm
