<div class="portlet">
	<div class="portlet-heading bg-danger">
		<h3 class="portlet-title">
			<?= $locale->_('Errors') ?>
		</h3>
		<div class="portlet-widgets">
			<a data-toggle="collapse" data-parent="#accordion1" href="#bg-warning"><i
					class="ion-minus-round"></i></a>
			<span class="divider"></span>
			<a href="#" data-toggle="remove"><i class="ion-close-round"></i></a>
		</div>
		<div class="clearfix"></div>
	</div>
	<div id="bg-warning" class="panel-collapse collapse in">
		<div class="portlet-body">
			<?php foreach ($errors as $error): ?>
				<p><?= $error ?></p>
			<?php endforeach; ?>
		</div>
	</div>
</div>